#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to your load-balancer IP (lb-01).
# Let’s also add other subdomains to make our life easier, 
# and write a Bash script that will display information about subdomains.

show_info ()
{
	res=( $(dig "$2.$1" | awk '/;; ANSWER SECTION:/{getline; print $4,$5}') )
	record=${res[0]}
	point=${res[1]}
	echo "The subdomain $2 is a $record record and points to $point"
}
if [ "$#" -eq 2 ]; then
	show_info "$1" "$2"
elif [ "$#" -eq 1 ]; then
	show_info "$1" www
	show_info "$1" lb-01
	show_info "$1" web-01
	show_info "$1" web-02
fi
