#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes

hour=0
min=1
while (( hour<13 ))
do
	echo "Hour: $hour"
	min=1
	while (( min<=59 ))
	do
		echo $min
		let min=min+1
	done
	let hour=hour+1
done
