#!/usr/bin/env bash
# nginx must be running as nginx user

sudo pkill apache2
sudo chmod ugo+rw /etc/nginx/nginx.conf
sed -i -E 's/(listen.*)80 /\18080 /g' /etc/nginx/sites-enabled/default
sudo -u nginx nginx
