#!/usr/bin/env bash
#  task #1, make your fix short and sweet

sudo pkill apache2
sudo chmod ugo+rw /etc/nginx/nginx.conf
sed -i -E 's/(listen.*)80 /\18080 /g' /etc/nginx/sites-enabled/default
sudo -u nginx nginx